
dataset:
  norm: True
  std4norm: 19325.2
  mean4norm: 23095.4
  dkey: 'sino' # n, 180, 574
  vh5:  '../dataset/ldp-valid.h5'
  th5:  '../dataset/ldp-train.h5'
  load2ram: True

train:
  mbsz: 128
  maxep: 500
  lr: 0.001
  ckp_steps: 10

model:
  enc_emb_dim: 1024
  dec_emb_dim: 1024
  enc_nlayer: 16
  dec_nlayer: 5
  enc_nhead: 16
  dec_nhead: 16 # dim should be divisible by num_heads
  mask_ratio: 0.6
