# GPT-3 Large similiar
dataset:
  norm: True
  std4norm: 19325.2
  mean4norm: 23095.4
  dkey: 'sino' # n, 180, 574
  vh5:  '../dataset/ldp-valid-resplit.h5'
  th5:  '../dataset/ldp-train-resplit.h5'
  load2ram: True

train:
  mbsz: 64
  maxep: 5000
  lr: 0.000003
  ckp_steps: 50

model:
  enc_emb_dim: 1536
  dec_emb_dim: 1536
  enc_nlayer: 24
  dec_nlayer: 24
  enc_nhead: 16
  dec_nhead: 16 # dim should be divisible by num_heads
  mask_ratio: 0.6
