
dataset:
  norm: False
  dkey: 'Ypdf'
  vh5:  'dataset/ds-valid.h5'
  th5:  'dataset/ds-train.h5'
  load2ram: True

train:
  mbsz: 256
  maxep: 200
  lr: 0.001
  ckp_steps: 1

model:
  enc_emb_dim: 512
  dec_emb_dim: 256
  enc_nlayer: 16
  dec_nlayer: 5
  enc_nhead: 16
  dec_nhead: 16
  mask_ratio: 0.5